version: "3.9"
services:
  postgres:
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /home/khristina/db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5433:5432"
