definitions:
  models.Modeling:
    properties:
      description:
        type: string
      image:
        type: string
      isDeleted:
        type: boolean
      modelingId:
        type: integer
      name:
        type: string
      price:
        type: number
    type: object
info:
  contact: {}
paths:
  /ping/{name}:
    get:
      description: very very friendly response
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Modeling'
      summary: Show hello text
      tags:
      - Tests
swagger: "2.0"
